Palm1r/QodeAssist

CMakeLists.txt
DocumentContextReader.cpp
DocumentContextReader.hpp
LLMClientInterface.cpp
QodeAssist.json.in
QodeAssistConstants.hpp
QodeAssistSettings.cpp
QodeAssistSettings.hpp
providers/OpenAICompatProvider.cpp
providers/OpenAICompatProvider.h
qodeassist.cpp
templates/CodeQwenChat.hpp

- Fix typo
- Fix remove comments from request
- Add support CodeQwenChat template (experimental)
- Add support OpenAI compatible provider (experimental)

Version 0.0.5

---

LLMClientInterface.cpp
QodeAssist.json.in
QodeAssistConstants.hpp
QodeAssistSettings.cpp
QodeAssistSettings.hpp
providers/LLMProvider.hpp
providers/LMStudioProvider.cpp
providers/LMStudioProvider.hpp
providers/OllamaProvider.cpp
providers/OllamaProvider.hpp
providers/OpenAICompatProvider.cpp
providers/OpenAICompatProvider.h

- Fix authorization to API
- Fix reset to provider default settings after reboot qtc

Version 0.0.6

---

DocumentContextReader.cpp
QodeAssistSettings.cpp
README.md

Version 0.0.9

---

QodeAssist.json.in
QodeAssistUtils.hpp
core/ChangesManager.cpp
settings/ContextSettings.cpp
settings/CustomPromptSettings.cpp
settings/GeneralSettings.cpp
settings/GeneralSettings.hpp
settings/PresetPromptsSettings.cpp

- Remove unnecessary log
- Improve settings

Version 0.1.3

---

QodeAssist.json.in
chat/ChatClientInterface.cpp
chat/ChatClientInterface.hpp
chat/ChatWidget.cpp
chat/ChatWidget.h
providers/LLMProvider.hpp
providers/LMStudioProvider.cpp
providers/LMStudioProvider.hpp
providers/OllamaProvider.cpp
providers/OllamaProvider.hpp
providers/OpenAICompatProvider.cpp
providers/OpenAICompatProvider.hpp
settings/GeneralSettings.cpp

- Fix getting models list from providers
- Fix clearing message history in chat
- Remove unnecessary logs

Version 0.2.1

---

QodeAssist.json.in
chatview/ChatUtils.cpp
chatview/qml/RootItem.qml
chatview/qml/dialog/CodeBlock.qml
qodeassist.cpp
templates/CodeLlamaChat.hpp

- Improve chat text input
- Add Llama chat support
- Fix monospace font

Version 0.3.1

---

QodeAssist.json.in
chatview/ChatModel.cpp
chatview/ChatModel.hpp
chatview/ChatRootView.cpp
chatview/ChatRootView.hpp
chatview/ClientInterface.cpp
chatview/ClientInterface.hpp
chatview/qml/RootItem.qml
llmcore/PromptTemplateManager.cpp
llmcore/ProvidersManager.cpp
llmcore/RequestHandler.cpp
settings/GeneralSettings.cpp

- Add streaming response to chat
- Add stopping chat request and button

Version 0.3.3

---

CMakeLists.txt
QodeAssist.json.in
chatview/qml/RootItem.qml
qodeassist.cpp
templates/Qwen.hpp

- Add support Qwen model for autocompete(FIM)
based on qwen2.5-coder:7b-base

Version 0.3.4

---

ConfigurationManager.cpp

Old code linked to fim provider, changed to chat provider now

Fix selecting chat models

---

ChatView/ChatModel.cpp
ChatView/ChatModel.hpp
ChatView/ClientInterface.cpp
DocumentContextReader.cpp
DocumentContextReader.hpp
LLMClientInterface.cpp
llmcore/ContextData.hpp
settings/CodeCompletionSettings.cpp
templates/CodeLlamaFim.hpp
templates/CustomFimTemplate.hpp
templates/DeepSeekCoderFim.hpp
templates/StarCoder2Fim.hpp

I used to save the context information directly into the user message for the model. Now I save it to the systemPrompt

Fix systemPrompt and context working

---

ConfigurationManager.cpp
llmcore/Provider.hpp
providers/LMStudioProvider.cpp
providers/LMStudioProvider.hpp
providers/OllamaProvider.cpp
providers/OllamaProvider.hpp
providers/OpenAICompatProvider.cpp
providers/OpenAICompatProvider.hpp
settings/CMakeLists.txt
settings/GeneralSettings.cpp
settings/GeneralSettings.hpp
settings/SettingsDialog.cpp
settings/SettingsDialog.hpp
settings/SettingsTr.hpp

- Added dialogs for selecting url, model and custom model when provider doesn't provide model list or setup of qode assist is not finishing

Impove UX general setting by added helpers dialogs for user

---

.github/workflows/build_cmake.yml
CMakeLists.txt
LLMSuggestion.cpp
LLMSuggestion.hpp
QodeAssist.json.in
QodeAssistClient.cpp
README.md
settings/ButtonAspect.hpp

- change api for Button Aspect
- change TextSuggestion
- change github action workflow

Upgrade plugin to Qt Creator 15

---

CodeHandler.hpp
test/CMakeLists.txt
test/CodeHandlerTest.cpp
test/DocumentContextReaderTest.cpp
test/TestUtils.hpp

Depends on https://github.com/Palm1r/QodeAssist/pull/104.

chore: Add tests for CodeHandler

---

CodeHandler.cpp
CodeHandler.hpp
LLMClientInterface.cpp
test/CodeHandlerTest.cpp

Revert "refactor: Move all processing logic to CodeHandler::processText()"

---

context/DocumentContextReader.cpp
test/DocumentContextReaderTest.cpp

Fixes https://github.com/Palm1r/QodeAssist/pull/98 by adding tests.

feat: Improve describe recent changes in system prompt

---

LLMClientInterface.cpp
LLMClientInterface.hpp
QodeAssistClient.cpp
QodeAssistClient.hpp
llmcore/CMakeLists.txt
llmcore/IProviderRegistry.hpp
llmcore/ProvidersManager.hpp
qodeassist.cpp

This will be needed for tests.

refactor: Decouple LLMClientInterface from ProvidersManager

---

LLMClientInterface.cpp
LLMClientInterface.hpp
llmcore/CMakeLists.txt
llmcore/RequestHandler.cpp
llmcore/RequestHandler.hpp
llmcore/RequestHandlerBase.cpp
llmcore/RequestHandlerBase.hpp
qodeassist.cpp

This will make it possible to write a mock implementation.

refactor: Introduce base class for RequestHandler

---

providers/OllamaProvider.cpp

Forgot this one with previous PR

fix: Add authorization while getting installed models (#142)

---

README.md

Added shortcut for Linux KDE Plasma

Minor Update README.md to include a shortcut on Linux

---

.github/workflows/build_cmake.yml

Add support 17.0.1 instead 17.0.0

feat: Add support QtCreator 17.0.1
