Palm1r/QodeAssist

providers/OpenAICompatProvider.cpp

The regression was introduced in https://github.com/Palm1r/QodeAssist/commit/bc93bce03bff3d5fe4d9d75f762514e1640dd259#diff-faab724bbfcfbc6687a3f5656c1ec01eee3bc398d533e868b2be7b71d9f6dcd5L85 which caused API key to not work.
This commit restores the ability to use API key.

Restore the ability to use API key

---

CMakeLists.txt
ChatView/ClientInterface.cpp
LLMClientInterface.cpp
qodeassist.cpp
settings/GeneralSettings.cpp
templates/Ollama.hpp

- Add OllamaAutoFim
- Use native Ollama API format when possible
- Remove need for manual template selection for most Ollama models
- Default to model-specific format from Ollama modelfile
- Fallback to manual template selection if needed
This change simplifies configuration by automatically using
the correct template format for each Ollama model.

feat: Add automatic template handling for Ollama models

---

CMakeLists.txt
CodeHandler.cpp
CodeHandler.hpp
LLMClientInterface.cpp
llmcore/CMakeLists.txt
llmcore/MessageBuilder.cpp
llmcore/MessageBuilder.hpp
llmcore/PromptTemplateManager.cpp
llmcore/PromptTemplateManager.hpp
llmcore/RequestHandler.cpp
providers/LMStudioProvider.cpp
providers/OllamaProvider.cpp
providers/OpenAICompatProvider.cpp
providers/OpenRouterAIProvider.cpp
settings/CodeCompletionSettings.cpp
settings/CodeCompletionSettings.hpp
settings/SettingsConstants.hpp

Add possibility to use instruct model in code

Add instract model in code completion

---

ChatView/CMakeLists.txt
ChatView/ChatRootView.cpp
ChatView/ChatRootView.hpp
ChatView/ChatSerializer.cpp
ChatView/ChatSerializer.hpp
ChatView/ChatUtils.h
ChatView/ClientInterface.cpp
ChatView/ClientInterface.hpp
ChatView/qml/Badge.qml
ChatView/qml/RootItem.qml
settings/ChatAssistantSettings.cpp
settings/ChatAssistantSettings.hpp
settings/ProjectSettings.cpp
settings/ProjectSettings.hpp
settings/ProjectSettingsPanel.cpp
settings/SettingsConstants.hpp

- Add path for chats history in projects settings
- Add buttons for loading and saving message list
- Add autosave option on message receiving
- Fix tokens badge width

Add saving and loading chat history

---

settings/SettingsConstants.hpp

These are duplicated in QodeAssistConstants.hpp. This prevents inclusion of both files into any source file anywhere in the project.

refactor: Remove duplicate constants from SettingsConstants.hpp

---

settings/GeneralSettings.cpp
settings/SettingsTr.hpp

It is possible to waste a lot of time searching for log messages, because Qt Creator already has a logging system which can be reached by going Tools > Debug Qt Creator > Show Logs. Adding a tooltip makes it possible to avoid this without introducing additional visual clutter.

fix: Add tooltip about where log messages can be seen

---

settings/GeneralSettings.cpp

Currently most dialogs follow the following order of action buttons: "OK", "Cancel" (left to right). However, several dialogs are constructed explicitly and don't follow this convention.
This commit fixes this discrepancy.
Fixes: https://github.com/Palm1r/QodeAssist/issues/83
New screenshot:

fix: Make settings dialogs button order consistent

---

qodeassist.cpp
settings/GeneralSettings.cpp

This introduces changes needed after the following commit in Qt Creator:
https://github.com/qt-creator/qt-creator/commit/ba5e4b7eff81bf84eb359df3bf5730d7a2a04588 Core: Provide settings categories centrally

fix: Make plugin registration be compatible with Qt Creator 16

---

settings/GeneralSettings.cpp

Sorry for not formatting one of my past commits.
I will add formatting check as part of CI in separate PR.
This commit is a result of the following commands:
```
clang-format-19 --style=file -i $(git ls-files | fgrep .cpp) 
clang-format-19 --style=file -i $(git ls-files | fgrep .hpp)
```

chore: Run clang-format over the codebase

---

.github/workflows/check_formatting.yml

This ensures that broken formatting is not accidentally merged. This would break user workflow because then they cannot format their code without introducing unrelated changes.

chore: Add Github Actions job for checking formatting

---

LLMClientInterface.cpp
context/DocumentContextReader.cpp
context/DocumentContextReader.hpp

This makes it possible to write simple unit tests for it without running full Qt Creator. Not coupling DocumentContextReader to TextEditor::TextDocument unnecessarily is also a better design in general.

refactor: Make DocumentContextReader usable outside Qt Creator context

---

.github/workflows/build_cmake.yml
CMakeLists.txt
test/CMakeLists.txt
test/DocumentContextReaderTest.cpp
test/unittest_main.cpp

The tests are based on GTest like some tests in Qt Creator itself, which makes it easy to run as full Qt Creator does not need to be started.
Depends on #89 landing.

chore: Add unit tests for DocumentContextReader 

---

context/DocumentContextReader.cpp
context/DocumentContextReader.hpp
test/DocumentContextReaderTest.cpp

Currently the current line is duplicated in both "before" and "after" context. This is due to `DocumentContextReader::readWholeFileAfter()` picking the current line part of which has been already included into the "before" context.

fix: Correctly pick whole file context

---

context/DocumentContextReader.cpp
context/DocumentContextReader.hpp
test/DocumentContextReaderTest.cpp

This also specifies what exactly getContext*() functions do. Before this commit linesCount was sometimes interpreted as exclusive of current line, which was confusing as linesCount + 1 lines were being returned.
Depends on https://github.com/Palm1r/QodeAssist/pull/85. Some issues with copyright handling have been uncovered, these will be fixed in subsequent PR.

fix: Fix off by one errors in getContext{Before,After}()

---

context/DocumentContextReader.cpp

getContextAfter(int lineNumber, int cursorPosition) and getContextBefore(int lineNumber, int cursorPosition) are currently not tested. Thus as little logic as possible should live there.

refactor: Reuse getContext{Before,After}() instead of duplicating logic

---

LLMClientInterface.cpp
context/DocumentContextReader.cpp
context/DocumentContextReader.hpp
llmcore/ContextData.hpp
test/DocumentContextReaderTest.cpp

This involves inlining getContextBefore() and getContextAfter() which contained relatively simple and duplicated logic and exposing code completion settings to the caller. This allows writing tests for prepareContext() which was done in this commit.
The tests recovered that I changed meaning of `linesCount` after all in previous PR, so callers will need adjustments. I will fix this in next PR as this is refactoring commit.

refactor: Make DocumentContextReader::prepareContext() testable

---

context/DocumentContextReader.cpp
test/DocumentContextReaderTest.cpp

A previous commit changed what linesCount argument of getContext{After,Before} meant. The callers relied on the old meaning. This commit fixes this.
Fixes: https://github.com/Palm1r/QodeAssist/commit/3dc0d910bfaf3bd56eaec3bd476631a471b36109

fix: Bring back old behavior of readStrings{After,Before}Cursor setting 

---

.github/workflows/build_cmake.yml

As we review before, will be better to save linux building state on ubuntu 22.04

feat: Change linux build base to ubuntu 22.04

---

test/DocumentContextReaderTest.cpp

Previously QString was printed symbol by symbol. E.g.:
```
reader.readWholeFileAfter(3, 1)
Which is: { "i", "n", "e", " ", "2", "
", "L", "i", "n", "e", " ", "3" }
```

chore: Fix pretty printing for QString

---

test/DocumentContextReaderTest.cpp

Tests should have "before" and "after" cases side by side, so that it's possible to easily verify that full context is extracted correctly.
Also tests should consistently cover the same conditions in all the different scenarios.

chore: Expand DocumentContextReaderTest to cover more conditions

---

context/DocumentContextReader.cpp
context/DocumentContextReader.hpp
test/DocumentContextReaderTest.cpp

This commit ensures that copyright information is always excluded and that context is always split into prefix and suffix at correct position.

fix: Properly omit copyright information

---

CodeHandler.cpp
CodeHandler.hpp
LLMClientInterface.cpp
test/CodeHandlerTest.cpp

This will become useful once more processing modes are available

refactor: Move all processing logic to CodeHandler::processText()

---

test/unittest_main.cpp

Currently tests emit a lot of warnings like:
Accessing MimeDatabase for text/python before plugins are initialized
or
SOFT ASSERT [<...>]: "theSettings" in <..>/src/libs/utils/aspects.cpp
These make navigating test output difficult. The warnings are mostly useless in tests, so these can be disabled.
If this ever becomes a problem, the code can be enhanced to re-enable tests via environment variable.

chore: Silence Qt warnings during tests

---

CodeHandler.cpp
CodeHandler.hpp
LLMClientInterface.cpp
test/CodeHandlerTest.cpp

This makes it possible to represent code blocks in models that emit their suggestion immediately after the ``` characters.

fix: Improve support for code blocks without language

---

LLMClientInterface.cpp
context/ContextManager.cpp
context/ContextManager.hpp

Using global state makes testing things way harder.

refactor: Don't use global state in ContextManager::isSpecifyCompletion

---

settings/CodeCompletionSettings.cpp

The same call is several lines below.
Note that systemPrompt does not need label due to a similarly named checkbox placed nearby. Thus users intuitively know what the text box is for.

chore: Remove duplicate label setting for systemPromptForNonFimModels

---

LLMClientInterface.cpp
LLMClientInterface.hpp
QodeAssistClient.cpp
settings/CodeCompletionSettings.cpp
settings/CodeCompletionSettings.hpp

This reduces reliance on global state and makes it more possible to test the code.

refactor: Inject settings into LLMClientInterface

---

ChatView/ChatRootView.cpp
ChatView/ClientInterface.cpp
context/ContextManager.cpp
settings/ProjectSettings.cpp

This solves a number of deprecation warnings during build. FilePath::toFSPathString() has been available since couple of years ago.

chore: Replace deprecated FilePath::toString() with toFSPathString()

---

ChatView/ChatRootView.cpp
ChatView/ChatRootView.hpp
ChatView/ClientInterface.cpp
ChatView/ClientInterface.hpp
LLMClientInterface.cpp
LLMClientInterface.hpp
QodeAssistClient.cpp
QodeAssistClient.hpp
llmcore/CMakeLists.txt
llmcore/IPromptProvider.hpp
llmcore/PromptProviderChat.hpp
llmcore/PromptProviderFim.hpp
qodeassist.cpp

This makes it possible to test the user classes

refactor: Decouple prompt template manager from their users

---

QodeAssistClient.cpp
QodeAssistClient.hpp
qodeassist.cpp

Contructing LLMClientInterface in constructor of QodeAssistClient when initializing base class severely limits what can be done. In particular, no members can be referred to, because nothing of the class instance itself has been initialized at that point of time.

refactor: Pass LLMClientInterface to QodeAssistClient

---

LLMClientInterface.cpp
LLMClientInterface.hpp
logger/CMakeLists.txt
logger/EmptyRequestPerformanceLogger.hpp
logger/IRequestPerformanceLogger.hpp
logger/RequestPerformanceLogger.cpp
logger/RequestPerformanceLogger.hpp
qodeassist.cpp

This should not be responsibility of LLMClientInterface. Extracting this class also adds flexibility to silence logging output in tests.

refactor: Extract performance logging to separate class

---

LLMClientInterface.cpp
LLMClientInterface.hpp
context/CMakeLists.txt
context/DocumentReaderQtCreator.hpp
context/IDocumentReader.hpp
qodeassist.cpp

This decouples LLMClientInterface from Qt Creator text editor implementation and allows to write tests

refactor: Extract document reading to separate class

---

llmcore/RequestHandler.cpp
llmcore/RequestHandler.hpp

Fixes "QObject: Cannot create children for a parent that is in a different thread" error by creating QNetworkAccessManager in the same thread where it's used, ensuring proper thread affinity for network operations.

fix: Resolve thread-related QNetworkAccessManager issue
